#!/bin/sh
#/etc/init.d/sion-wireless

case "$1" in
	start)
		echo "SION: Starting wireless..."
		ifup wlan0
		;;
	stop)
		echo "SION: Stopping wireless..."
		ifdown wlan0
		;;
	*)
		echo "Usage: /etc/init.d/sion-wireless {start|stop}"
		exit 1
esac

exit 0 
